import type { SeedPack } from '../types';

/**
 * Fashion-workshop starter pack — Ankara / ready-to-wear shops that
 * produce in small lots. Materials are mostly metres of fabric +
 * trims; recipes capture the per-garment fabric budget so the
 * shortage engine catches "we can't cut another wrap dress, only
 * 0.5 m of red ankara left."
 */
export const FASHION_PACK: SeedPack = {
  id: 'fashion',
  label: 'Fashion workshop',
  description:
    'Starter pack for tailoring shops — Ankara, ready-to-wear, dresses, shirts, agbada.',
  emoji: '👗',

  materials: [
    // ── FABRIC ───────────────────────────────────────────────────
    {
      // We store fabric in cm rather than metres so quantities can stay
      // whole-integer (a peplum top wants 180 cm of ankara, not 1.8 m).
      name: 'Ankara fabric',
      unit: 'cm',
      materialType: 'COMPONENT',
      category: 'Fabric',
      unitCostKobo: 1500,
      reorderLevel: 1000,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'White cotton lining',
      unit: 'cm',
      materialType: 'COMPONENT',
      category: 'Fabric',
      unitCostKobo: 600,
      reorderLevel: 1000,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Aso oke trim',
      unit: 'cm',
      materialType: 'COMPONENT',
      category: 'Fabric',
      unitCostKobo: 3200,
      reorderLevel: 200,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 7,
    },
    {
      name: 'Cotton shirting (premium)',
      unit: 'cm',
      materialType: 'COMPONENT',
      category: 'Fabric',
      unitCostKobo: 1100,
      reorderLevel: 500,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 5,
    },

    // ── TRIMS & NOTIONS ──────────────────────────────────────────
    {
      name: 'Invisible zipper (50 cm)',
      unit: 'unit',
      materialType: 'COMPONENT',
      category: 'Notions',
      unitCostKobo: 8000,
      reorderLevel: 30,
      minimumPurchaseQuantity: 24,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Plastic button (15 mm)',
      unit: 'unit',
      materialType: 'COMPONENT',
      category: 'Notions',
      unitCostKobo: 1500,
      reorderLevel: 200,
      minimumPurchaseQuantity: 144,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Cotton thread (500 m spool)',
      unit: 'unit',
      materialType: 'CONSUMABLE',
      category: 'Notions',
      unitCostKobo: 6000,
      reorderLevel: 10,
      minimumPurchaseQuantity: 12,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Interfacing (cm)',
      unit: 'cm',
      materialType: 'COMPONENT',
      category: 'Notions',
      unitCostKobo: 800,
      reorderLevel: 500,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 3,
    },

    // ── PACKAGING ────────────────────────────────────────────────
    {
      name: 'Garment bag',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Packaging',
      unitCostKobo: 15000,
      reorderLevel: 30,
      minimumPurchaseQuantity: 50,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Branded hang tag',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Labels',
      unitCostKobo: 8000,
      reorderLevel: 100,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 7,
    },
  ],

  products: [
    {
      name: 'Ankara wrap dress',
      sku: 'FS-AWD',
      priceKobo: 2_500_000,
      costKobo: 900_000,
      lowStockAt: 3,
      category: 'Dresses',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Ankara A-line skirt',
      sku: 'FS-ASK',
      priceKobo: 1_200_000,
      costKobo: 420_000,
      lowStockAt: 4,
      category: 'Bottoms',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Fitted blouse',
      sku: 'FS-FBL',
      priceKobo: 1_500_000,
      costKobo: 550_000,
      lowStockAt: 4,
      category: 'Tops',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Long kaftan',
      sku: 'FS-LKF',
      priceKobo: 2_200_000,
      costKobo: 800_000,
      lowStockAt: 3,
      category: 'Dresses',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Peplum top',
      sku: 'FS-PEP',
      priceKobo: 1_400_000,
      costKobo: 480_000,
      lowStockAt: 4,
      category: 'Tops',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Agbada (premium)',
      sku: 'FS-AGB',
      priceKobo: 9_500_000,
      costKobo: 3_200_000,
      lowStockAt: 2,
      category: 'Traditional',
      canBeProduced: true,
      defaultBatchSize: 3,
    },
    {
      name: 'Tailored shirt',
      sku: 'FS-SHT',
      priceKobo: 1_800_000,
      costKobo: 650_000,
      lowStockAt: 4,
      category: 'Tops',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Ankara jumpsuit',
      sku: 'FS-JMP',
      priceKobo: 2_800_000,
      costKobo: 1_050_000,
      lowStockAt: 3,
      category: 'Sets',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
  ],

  recipes: [
    {
      productName: 'Ankara wrap dress',
      yieldQty: 5,
      notes: 'Cut on the cross-grain for swing. Press seams before joining.',
      items: [
        { materialName: 'Ankara fabric', quantity: 1500 },
        { materialName: 'White cotton lining', quantity: 800 },
        { materialName: 'Invisible zipper (50 cm)', quantity: 5 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Ankara A-line skirt',
      yieldQty: 5,
      notes: 'Hem with blind stitch.',
      items: [
        { materialName: 'Ankara fabric', quantity: 750 },
        { materialName: 'Invisible zipper (50 cm)', quantity: 5 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Fitted blouse',
      yieldQty: 5,
      notes: 'Interface the collar + cuffs.',
      items: [
        { materialName: 'Cotton shirting (premium)', quantity: 900 },
        { materialName: 'Interfacing (cm)', quantity: 100 },
        { materialName: 'Plastic button (15 mm)', quantity: 35 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Long kaftan',
      yieldQty: 5,
      notes: 'Aso oke trim along the neckline + sleeves.',
      items: [
        { materialName: 'Ankara fabric', quantity: 1600 },
        { materialName: 'Aso oke trim', quantity: 300 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Peplum top',
      yieldQty: 5,
      notes: 'Lined bodice. Back invisible zip.',
      items: [
        { materialName: 'Ankara fabric', quantity: 900 },
        { materialName: 'White cotton lining', quantity: 400 },
        { materialName: 'Invisible zipper (50 cm)', quantity: 5 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Agbada (premium)',
      yieldQty: 3,
      notes: 'Three-piece set. Hand-embroidered neckline. Allow 3 days curing.',
      items: [
        { materialName: 'Cotton shirting (premium)', quantity: 2100 },
        { materialName: 'Aso oke trim', quantity: 600 },
        { materialName: 'Plastic button (15 mm)', quantity: 30 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 2 },
        { materialName: 'Branded hang tag', quantity: 3 },
        { materialName: 'Garment bag', quantity: 3 },
      ],
    },
    {
      productName: 'Tailored shirt',
      yieldQty: 5,
      notes: 'Topstitch collar + placket.',
      items: [
        { materialName: 'Cotton shirting (premium)', quantity: 1100 },
        { materialName: 'Interfacing (cm)', quantity: 80 },
        { materialName: 'Plastic button (15 mm)', quantity: 40 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
    {
      productName: 'Ankara jumpsuit',
      yieldQty: 5,
      notes: 'Wide-leg cut. Back invisible zip.',
      items: [
        { materialName: 'Ankara fabric', quantity: 1700 },
        { materialName: 'White cotton lining', quantity: 600 },
        { materialName: 'Invisible zipper (50 cm)', quantity: 5 },
        { materialName: 'Cotton thread (500 m spool)', quantity: 1 },
        { materialName: 'Branded hang tag', quantity: 5 },
        { materialName: 'Garment bag', quantity: 5 },
      ],
    },
  ],
};
