import type { SeedPack } from '../types';

/**
 * Food-processor starter pack — packaged palm oil + spice blends + ground
 * seeds, the typical Aba / Onitsha / Kano food workshop. Includes the
 * NAFDAC-relevant fields (batch-friendly recipe sizes, jar/label
 * packaging) so the production loop is ready for traceability.
 *
 * Money is kobo (Int). Materials in smallest base unit (g/ml/unit) so
 * RecipeItem.quantity stays whole-integer.
 */
export const FOOD_PACK: SeedPack = {
  id: 'food',
  label: 'Food processor',
  description:
    'Starter pack for packaged food workshops — palm oil bottling, spice blends, dry goods.',
  emoji: '🍲',

  materials: [
    // ── INGREDIENTS ──────────────────────────────────────────────
    {
      name: 'Raw palm oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Oils',
      unitCostKobo: 180,
      reorderLevel: 10000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Groundnut oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Oils',
      unitCostKobo: 250,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Dry pepper (ata gungun)',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Spices',
      unitCostKobo: 80,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Crayfish powder',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Spices',
      unitCostKobo: 180,
      reorderLevel: 2000,
      minimumPurchaseQuantity: 1000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Suya spice blend (yaji)',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Spices',
      unitCostKobo: 220,
      reorderLevel: 2000,
      minimumPurchaseQuantity: 1000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Iodised salt',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Seasoning',
      unitCostKobo: 8,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 2,
    },
    {
      name: 'Egusi seed (raw)',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Dry goods',
      unitCostKobo: 110,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Groundnut (raw, shelled)',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Dry goods',
      unitCostKobo: 75,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },

    // ── PACKAGING ────────────────────────────────────────────────
    {
      name: '200 ml PET bottle',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Bottles',
      unitCostKobo: 8000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
    {
      name: '500 ml PET bottle',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Bottles',
      unitCostKobo: 15000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
    {
      name: '1 L PET bottle',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Bottles',
      unitCostKobo: 25000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
    {
      name: '100 g spice sachet',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Sachets',
      unitCostKobo: 4000,
      reorderLevel: 100,
      minimumPurchaseQuantity: 200,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Stand-up zip pouch (250 g)',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Sachets',
      unitCostKobo: 7000,
      reorderLevel: 100,
      minimumPurchaseQuantity: 200,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Product label',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Labels',
      unitCostKobo: 15000,
      reorderLevel: 200,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
  ],

  products: [
    {
      name: 'Palm oil — 200 ml',
      sku: 'FD-PO-200',
      priceKobo: 70_000,
      costKobo: 41_000,
      lowStockAt: 12,
      category: 'Oils',
      canBeProduced: true,
      defaultBatchSize: 20,
    },
    {
      name: 'Palm oil — 500 ml',
      sku: 'FD-PO-500',
      priceKobo: 150_000,
      costKobo: 90_000,
      lowStockAt: 10,
      category: 'Oils',
      canBeProduced: true,
      defaultBatchSize: 20,
    },
    {
      name: 'Palm oil — 1 L',
      sku: 'FD-PO-1000',
      priceKobo: 280_000,
      costKobo: 180_000,
      lowStockAt: 8,
      category: 'Oils',
      canBeProduced: true,
      defaultBatchSize: 20,
    },
    {
      name: 'Pepper powder — 100 g',
      sku: 'FD-PP-100',
      priceKobo: 80_000,
      costKobo: 30_000,
      lowStockAt: 10,
      category: 'Spices',
      canBeProduced: true,
      defaultBatchSize: 20,
    },
    {
      name: 'Suya spice — 100 g',
      sku: 'FD-SS-100',
      priceKobo: 100_000,
      costKobo: 40_000,
      lowStockAt: 10,
      category: 'Spices',
      canBeProduced: true,
      defaultBatchSize: 20,
    },
    {
      name: 'Egusi powder — 250 g',
      sku: 'FD-EG-250',
      priceKobo: 120_000,
      costKobo: 50_000,
      lowStockAt: 8,
      category: 'Dry goods',
      canBeProduced: true,
      defaultBatchSize: 15,
    },
    {
      name: 'Roasted groundnut — 250 g',
      sku: 'FD-GN-250',
      priceKobo: 90_000,
      costKobo: 38_000,
      lowStockAt: 10,
      category: 'Dry goods',
      canBeProduced: true,
      defaultBatchSize: 15,
    },
    {
      name: 'Crayfish powder — 100 g',
      sku: 'FD-CF-100',
      priceKobo: 150_000,
      costKobo: 70_000,
      lowStockAt: 8,
      category: 'Spices',
      canBeProduced: true,
      defaultBatchSize: 15,
    },
  ],

  recipes: [
    {
      productName: 'Palm oil — 200 ml',
      yieldQty: 20,
      notes: 'Filter twice through cheesecloth before bottling. Check sediment.',
      items: [
        { materialName: 'Raw palm oil', quantity: 4200 },
        { materialName: '200 ml PET bottle', quantity: 20 },
        { materialName: 'Product label', quantity: 20 },
      ],
    },
    {
      productName: 'Palm oil — 500 ml',
      yieldQty: 20,
      notes: 'Filter twice. Heat-seal cap shrink-wrap.',
      items: [
        { materialName: 'Raw palm oil', quantity: 10300 },
        { materialName: '500 ml PET bottle', quantity: 20 },
        { materialName: 'Product label', quantity: 20 },
      ],
    },
    {
      productName: 'Palm oil — 1 L',
      yieldQty: 20,
      notes: 'NAFDAC batch number on every bottle.',
      items: [
        { materialName: 'Raw palm oil', quantity: 20500 },
        { materialName: '1 L PET bottle', quantity: 20 },
        { materialName: 'Product label', quantity: 20 },
      ],
    },
    {
      productName: 'Pepper powder — 100 g',
      yieldQty: 20,
      notes: 'Dry-grind to fine. Stir in 5% salt to prevent caking.',
      items: [
        { materialName: 'Dry pepper (ata gungun)', quantity: 2000 },
        { materialName: 'Iodised salt', quantity: 100 },
        { materialName: '100 g spice sachet', quantity: 20 },
        { materialName: 'Product label', quantity: 20 },
      ],
    },
    {
      productName: 'Suya spice — 100 g',
      yieldQty: 20,
      notes: 'Mix yaji blend with crayfish powder + salt. Sieve before packing.',
      items: [
        { materialName: 'Suya spice blend (yaji)', quantity: 1600 },
        { materialName: 'Crayfish powder', quantity: 300 },
        { materialName: 'Iodised salt', quantity: 100 },
        { materialName: '100 g spice sachet', quantity: 20 },
        { materialName: 'Product label', quantity: 20 },
      ],
    },
    {
      productName: 'Egusi powder — 250 g',
      yieldQty: 15,
      notes: 'Toast lightly before grinding for richer flavour.',
      items: [
        { materialName: 'Egusi seed (raw)', quantity: 3800 },
        { materialName: 'Stand-up zip pouch (250 g)', quantity: 15 },
        { materialName: 'Product label', quantity: 15 },
      ],
    },
    {
      productName: 'Roasted groundnut — 250 g',
      yieldQty: 15,
      notes: 'Roast at 160 °C for 12 min — cool before bagging.',
      items: [
        { materialName: 'Groundnut (raw, shelled)', quantity: 3800 },
        { materialName: 'Iodised salt', quantity: 50 },
        { materialName: 'Stand-up zip pouch (250 g)', quantity: 15 },
        { materialName: 'Product label', quantity: 15 },
      ],
    },
    {
      productName: 'Crayfish powder — 100 g',
      yieldQty: 15,
      notes: 'Sun-dry overnight before grinding. Sift to fine powder.',
      items: [
        { materialName: 'Crayfish powder', quantity: 1500 },
        { materialName: '100 g spice sachet', quantity: 15 },
        { materialName: 'Product label', quantity: 15 },
      ],
    },
  ],
};
