import type { SeedPack } from '../types';

/**
 * Printing-shop starter pack — small-format shops (Yaba, Computer
 * Village) doing business cards, flyers, banners, stickers, brochures.
 * Materials are mostly sheet counts + ink consumption per batch.
 */
export const PRINTING_PACK: SeedPack = {
  id: 'printing',
  label: 'Printing shop',
  description:
    'Starter pack for print shops — business cards, flyers, banners, stickers, brochures.',
  emoji: '🖨️',

  materials: [
    {
      name: 'A4 cardstock (300 gsm)',
      unit: 'sheet',
      materialType: 'COMPONENT',
      category: 'Paper',
      unitCostKobo: 4500,
      reorderLevel: 200,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'A3 cardstock (300 gsm)',
      unit: 'sheet',
      materialType: 'COMPONENT',
      category: 'Paper',
      unitCostKobo: 8500,
      reorderLevel: 100,
      minimumPurchaseQuantity: 250,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'A4 glossy paper (170 gsm)',
      unit: 'sheet',
      materialType: 'COMPONENT',
      category: 'Paper',
      unitCostKobo: 3000,
      reorderLevel: 200,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'A4 sticker paper',
      unit: 'sheet',
      materialType: 'COMPONENT',
      category: 'Paper',
      unitCostKobo: 12000,
      reorderLevel: 100,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'A4 laminate film (matte)',
      unit: 'sheet',
      materialType: 'COMPONENT',
      category: 'Finishing',
      unitCostKobo: 8000,
      reorderLevel: 100,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Inkjet ink (CMYK set)',
      unit: 'ml',
      materialType: 'CONSUMABLE',
      category: 'Ink',
      unitCostKobo: 1200,
      reorderLevel: 500,
      minimumPurchaseQuantity: 250,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Banner vinyl (sqcm)',
      unit: 'sqcm',
      materialType: 'COMPONENT',
      category: 'Wide-format',
      unitCostKobo: 30,
      reorderLevel: 50000,
      minimumPurchaseQuantity: 50000,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Brand wrap pouch',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Packaging',
      unitCostKobo: 7000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
  ],

  products: [
    {
      name: 'Business cards (100/pack)',
      sku: 'PR-BC-100',
      priceKobo: 350_000,
      costKobo: 110_000,
      lowStockAt: 6,
      category: 'Cards',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'A5 flyers (100/pack)',
      sku: 'PR-A5-100',
      priceKobo: 280_000,
      costKobo: 120_000,
      lowStockAt: 6,
      category: 'Flyers',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'A4 flyers (100/pack)',
      sku: 'PR-A4-100',
      priceKobo: 450_000,
      costKobo: 180_000,
      lowStockAt: 4,
      category: 'Flyers',
      canBeProduced: true,
      defaultBatchSize: 5,
    },
    {
      name: 'Tri-fold brochure (50/pack)',
      sku: 'PR-BR-050',
      priceKobo: 500_000,
      costKobo: 210_000,
      lowStockAt: 4,
      category: 'Brochures',
      canBeProduced: true,
      defaultBatchSize: 3,
    },
    {
      name: 'A4 sticker sheet (10/pack)',
      sku: 'PR-ST-010',
      priceKobo: 180_000,
      costKobo: 75_000,
      lowStockAt: 8,
      category: 'Stickers',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Roll-up banner (80×200 cm)',
      sku: 'PR-RB-80200',
      priceKobo: 2_500_000,
      costKobo: 950_000,
      lowStockAt: 2,
      category: 'Wide-format',
      canBeProduced: true,
      defaultBatchSize: 2,
    },
  ],

  recipes: [
    {
      productName: 'Business cards (100/pack)',
      yieldQty: 5,
      notes: 'Print 10-up on A4 cardstock. Trim with guillotine.',
      items: [
        { materialName: 'A4 cardstock (300 gsm)', quantity: 50 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 12 },
        { materialName: 'A4 laminate film (matte)', quantity: 50 },
        { materialName: 'Brand wrap pouch', quantity: 5 },
      ],
    },
    {
      productName: 'A5 flyers (100/pack)',
      yieldQty: 5,
      notes: 'Print 2-up on A4 glossy. Slit down the centre.',
      items: [
        { materialName: 'A4 glossy paper (170 gsm)', quantity: 250 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 30 },
        { materialName: 'Brand wrap pouch', quantity: 5 },
      ],
    },
    {
      productName: 'A4 flyers (100/pack)',
      yieldQty: 5,
      notes: '500 sheets per batch — heaviest ink load of any product.',
      items: [
        { materialName: 'A4 glossy paper (170 gsm)', quantity: 500 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 75 },
        { materialName: 'Brand wrap pouch', quantity: 5 },
      ],
    },
    {
      productName: 'Tri-fold brochure (50/pack)',
      yieldQty: 3,
      notes: 'A4 landscape, score + fold. Use bone folder for crisp creases.',
      items: [
        { materialName: 'A4 cardstock (300 gsm)', quantity: 150 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 50 },
        { materialName: 'Brand wrap pouch', quantity: 3 },
      ],
    },
    {
      productName: 'A4 sticker sheet (10/pack)',
      yieldQty: 10,
      notes: 'Print direct to sticker paper. Kiss-cut + back-slit.',
      items: [
        { materialName: 'A4 sticker paper', quantity: 100 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 20 },
        { materialName: 'Brand wrap pouch', quantity: 10 },
      ],
    },
    {
      productName: 'Roll-up banner (80×200 cm)',
      yieldQty: 2,
      notes: 'Print on banner vinyl, fit to retractable hardware. 80 × 200 cm = 16,000 sqcm each.',
      items: [
        { materialName: 'Banner vinyl (sqcm)', quantity: 32000 },
        { materialName: 'Inkjet ink (CMYK set)', quantity: 80 },
      ],
    },
  ],
};
