import type { SeedPack } from '../types';

/**
 * Skincare-maker starter pack — modeled on a typical Lagos / Abuja
 * small-batch skincare workshop (Black soap, body butters, face serums,
 * carrier oil blends). Quantities calibrated to a per-batch yield of
 * 10 units so the math stays whole-integer across all RecipeItem rows.
 *
 * Money is kobo (Int). Where the unit cost is "per gram" or "per ml",
 * `unitCostKobo` represents the cost for one whole base unit. Example:
 * shea butter at ₦4.50/g → unitCostKobo = 450.
 *
 * All quantities below are in the material's stored unit. So 2000 g of
 * shea butter, 100 ml of lavender oil, 10 jars, 10 labels. Whole ints.
 */
export const SKINCARE_PACK: SeedPack = {
  id: 'skincare',
  label: 'Skincare maker',
  description:
    'Starter pack for small-batch skincare workshops — body butters, soaps, oils, serums.',
  emoji: '🧴',

  materials: [
    // ── INGREDIENTS ──────────────────────────────────────────────
    {
      name: 'Raw shea butter',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Butters',
      unitCostKobo: 450,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Cocoa butter',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Butters',
      unitCostKobo: 520,
      reorderLevel: 2000,
      minimumPurchaseQuantity: 1000,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Coconut oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Carrier oils',
      unitCostKobo: 380,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Olive oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Carrier oils',
      unitCostKobo: 600,
      reorderLevel: 2000,
      minimumPurchaseQuantity: 1000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Castor oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Carrier oils',
      unitCostKobo: 420,
      reorderLevel: 2000,
      minimumPurchaseQuantity: 1000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Sweet almond oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Carrier oils',
      unitCostKobo: 1200,
      reorderLevel: 1000,
      minimumPurchaseQuantity: 500,
      expectedLeadTimeDays: 7,
    },
    {
      name: 'Lavender essential oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Essential oils',
      unitCostKobo: 4000,
      reorderLevel: 200,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 7,
    },
    {
      name: 'Tea tree essential oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Essential oils',
      unitCostKobo: 3500,
      reorderLevel: 200,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 7,
    },
    {
      name: 'Black soap base',
      unit: 'g',
      materialType: 'INGREDIENT',
      category: 'Soap',
      unitCostKobo: 350,
      reorderLevel: 5000,
      minimumPurchaseQuantity: 5000,
      expectedLeadTimeDays: 3,
    },
    {
      name: 'Vitamin E oil',
      unit: 'ml',
      materialType: 'INGREDIENT',
      category: 'Actives',
      unitCostKobo: 2500,
      reorderLevel: 100,
      minimumPurchaseQuantity: 50,
      expectedLeadTimeDays: 5,
    },

    // ── PACKAGING ────────────────────────────────────────────────
    {
      name: '200 ml plastic jar',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Containers',
      unitCostKobo: 15000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 50,
      expectedLeadTimeDays: 5,
    },
    {
      name: '50 g jar',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Containers',
      unitCostKobo: 8000,
      reorderLevel: 50,
      minimumPurchaseQuantity: 50,
      expectedLeadTimeDays: 5,
    },
    {
      name: 'Product label',
      unit: 'unit',
      materialType: 'PACKAGING',
      category: 'Labels',
      unitCostKobo: 20000,
      reorderLevel: 200,
      minimumPurchaseQuantity: 100,
      expectedLeadTimeDays: 5,
    },
  ],

  products: [
    {
      name: 'Black soap bar (200 g)',
      sku: 'SK-BLK-200',
      priceKobo: 150_000,
      costKobo: 95_000,
      lowStockAt: 8,
      category: 'Soap',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Body butter (200 g)',
      sku: 'SK-BBT-200',
      priceKobo: 450_000,
      costKobo: 175_000,
      lowStockAt: 6,
      category: 'Butters',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Carrier oil blend (200 ml)',
      sku: 'SK-COB-200',
      priceKobo: 320_000,
      costKobo: 145_000,
      lowStockAt: 6,
      category: 'Oils',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Face serum (50 g)',
      sku: 'SK-FSR-050',
      priceKobo: 550_000,
      costKobo: 195_000,
      lowStockAt: 6,
      category: 'Serums',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Lavender body cream (200 g)',
      sku: 'SK-LBC-200',
      priceKobo: 500_000,
      costKobo: 220_000,
      lowStockAt: 6,
      category: 'Creams',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Tea tree spot treatment (50 g)',
      sku: 'SK-TTS-050',
      priceKobo: 350_000,
      costKobo: 150_000,
      lowStockAt: 6,
      category: 'Serums',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Olive oil hair serum (200 ml)',
      sku: 'SK-OHS-200',
      priceKobo: 400_000,
      costKobo: 175_000,
      lowStockAt: 6,
      category: 'Oils',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
    {
      name: 'Pure shea butter (200 g)',
      sku: 'SK-PSB-200',
      priceKobo: 350_000,
      costKobo: 120_000,
      lowStockAt: 6,
      category: 'Butters',
      canBeProduced: true,
      defaultBatchSize: 10,
    },
  ],

  // Each recipe yields 10 units of the product. Quantities are in the
  // material's stored unit (g / ml / unit). All whole integers.
  recipes: [
    {
      productName: 'Black soap bar (200 g)',
      yieldQty: 10,
      notes: 'Stir on low heat — never let the base boil. Cure 24h before packing.',
      items: [
        { materialName: 'Black soap base', quantity: 2000 },
        { materialName: 'Coconut oil', quantity: 200 },
        { materialName: 'Lavender essential oil', quantity: 20 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Body butter (200 g)',
      yieldQty: 10,
      notes: 'Whip butters at room temp for 5 minutes for the soft-peak texture.',
      items: [
        { materialName: 'Raw shea butter', quantity: 1500 },
        { materialName: 'Cocoa butter', quantity: 200 },
        { materialName: 'Coconut oil', quantity: 200 },
        { materialName: 'Vitamin E oil', quantity: 10 },
        { materialName: '200 ml plastic jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Carrier oil blend (200 ml)',
      yieldQty: 10,
      notes: 'Blend in a darkened bottle to preserve shelf life.',
      items: [
        { materialName: 'Olive oil', quantity: 1200 },
        { materialName: 'Sweet almond oil', quantity: 400 },
        { materialName: 'Castor oil', quantity: 400 },
        { materialName: 'Vitamin E oil', quantity: 20 },
        { materialName: '200 ml plastic jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Face serum (50 g)',
      yieldQty: 10,
      notes: 'Test pH between 5.0 and 5.5 before packing.',
      items: [
        { materialName: 'Sweet almond oil', quantity: 350 },
        { materialName: 'Olive oil', quantity: 100 },
        { materialName: 'Lavender essential oil', quantity: 20 },
        { materialName: 'Vitamin E oil', quantity: 30 },
        { materialName: '50 g jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Lavender body cream (200 g)',
      yieldQty: 10,
      notes: 'Cool below 40 °C before adding the essential oil.',
      items: [
        { materialName: 'Raw shea butter', quantity: 1200 },
        { materialName: 'Cocoa butter', quantity: 400 },
        { materialName: 'Coconut oil', quantity: 300 },
        { materialName: 'Lavender essential oil', quantity: 30 },
        { materialName: '200 ml plastic jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Tea tree spot treatment (50 g)',
      yieldQty: 10,
      notes: 'Strong essential-oil load — keep below 5% concentration.',
      items: [
        { materialName: 'Raw shea butter', quantity: 300 },
        { materialName: 'Coconut oil', quantity: 100 },
        { materialName: 'Tea tree essential oil', quantity: 50 },
        { materialName: 'Vitamin E oil', quantity: 10 },
        { materialName: '50 g jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Olive oil hair serum (200 ml)',
      yieldQty: 10,
      notes: 'Decant into amber bottles when possible.',
      items: [
        { materialName: 'Olive oil', quantity: 1600 },
        { materialName: 'Castor oil', quantity: 200 },
        { materialName: 'Lavender essential oil', quantity: 20 },
        { materialName: '200 ml plastic jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
    {
      productName: 'Pure shea butter (200 g)',
      yieldQty: 10,
      notes: 'No additives — just clean, melt, pour, set, label.',
      items: [
        { materialName: 'Raw shea butter', quantity: 2000 },
        { materialName: '200 ml plastic jar', quantity: 10 },
        { materialName: 'Product label', quantity: 10 },
      ],
    },
  ],
};
